name: "autoversion"
on:
  push:
    branches:
      - "main"
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Generate release tag
        uses: cyberpwnn/next-release-tag@1.0.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Release Tag
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ env.release_tag  }}"
          prerelease: false
          title: "${{ env.release_tag  }}"
